#!/usr/bin/env bash
# Fetch app credentials from AWS SSM Parameter Store and write scripts/.env.
# Run from repo root: ./scripts/fetch-ssm-env.sh
#
# Required env vars (set before running, or export in your shell):
#   SSM_ENV        - Terraform workspace / environment name (e.g. nonprod)
#   SSM_APP        - App name as used in SSM paths (e.g. testapp)
#   AWS_REGION     - AWS region where parameters are stored (e.g. us-east-1)
#
# SSM paths read:
#   /{SSM_ENV}/{SSM_APP}/db/uri        -> DATABASE_URI
#   /{SSM_ENV}/{SSM_APP}/payload/secret -> PAYLOAD_SECRET
#
# The EC2 instance IAM role must have ssm:GetParameter + kms:Decrypt on these paths.
# No AWS credentials file is needed when running on the EC2 instance.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

: "${SSM_ENV:?SSM_ENV is required (e.g. nonprod)}"
: "${SSM_APP:?SSM_APP is required (e.g. testapp)}"
: "${AWS_REGION:?AWS_REGION is required (e.g. us-east-1)}"

fetch() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "Fetching SSM parameters for env=${SSM_ENV} app=${SSM_APP} region=${AWS_REGION}..."

DATABASE_URI="$(fetch "/${SSM_ENV}/${SSM_APP}/db/uri")"
PAYLOAD_SECRET="$(fetch "/${SSM_ENV}/${SSM_APP}/payload/secret")"

# Also fetch supporting values for reference / migrate script
DB_ENDPOINT="$(fetch "/${SSM_ENV}/${SSM_APP}/db/endpoint" 2>/dev/null || true)"
DB_NAME="$(fetch "/${SSM_ENV}/${SSM_APP}/db/name" 2>/dev/null || true)"

cat > "$ROOT/scripts/.env" <<EOF
# Generated by scripts/fetch-ssm-env.sh — do not edit manually.
# Re-run fetch-ssm-env.sh to refresh.

# RDS credentials (from SSM /${SSM_ENV}/${SSM_APP}/)
DATABASE_URI=${DATABASE_URI}
PAYLOAD_SECRET=${PAYLOAD_SECRET}

# Informational (not used by compose directly)
DB_ENDPOINT=${DB_ENDPOINT}
DB_NAME=${DB_NAME}

# Backend runtime
PAYLOAD_URL=${PAYLOAD_URL:-http://localhost:3001}
FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}

# Frontend (build-time baked by frontend.Dockerfile)
NEXT_PUBLIC_PAYLOAD_URL=${NEXT_PUBLIC_PAYLOAD_URL:-http://localhost:3001}
# Server-side API URL (container -> backend hostname in Docker network)
PAYLOAD_API_URL=${PAYLOAD_API_URL:-http://backend:3001}
EOF

echo "scripts/.env written."
