#!/usr/bin/env bash
# Fetch app credentials from AWS SSM Parameter Store and write scripts/.env.
# Run from repo root: ./scripts/fetch-ssm-env.sh
#
# Required env vars (set before running, or export in your shell):
#   SSM_ENV        - Terraform workspace / environment name (e.g. nonprod)
#   SSM_APP        - App name as used in SSM paths (e.g. testapp)
#   AWS_REGION     - AWS region where parameters are stored (e.g. us-east-1)
#
# SSM paths read:
#   /{SSM_ENV}/{SSM_APP}/db/uri        -> DATABASE_URI
#   /{SSM_ENV}/{SSM_APP}/payload/secret -> PAYLOAD_SECRET
#
# The EC2 instance IAM role must have ssm:GetParameter + kms:Decrypt on these paths.
# No AWS credentials file is needed when running on the EC2 instance.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

: "${SSM_ENV:?SSM_ENV is required (e.g. nonprod)}"
: "${SSM_APP:?SSM_APP is required (e.g. testapp)}"
: "${AWS_REGION:?AWS_REGION is required (e.g. us-east-1)}"

fetch() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "Fetching SSM parameters for env=${SSM_ENV} app=${SSM_APP} region=${AWS_REGION}..."

DATABASE_URI="$(fetch "/${SSM_ENV}/${SSM_APP}/db/uri")"
PAYLOAD_SECRET="$(fetch "/${SSM_ENV}/${SSM_APP}/payload/secret")"

# Detect public IP: prefer explicit override, then EC2 metadata, then localhost
if [ -n "${PUBLIC_IP:-}" ]; then
  HOST_IP="$PUBLIC_IP"
else
  HOST_IP="$(curl -sf --max-time 2 http://169.254.169.254/latest/meta-data/public-ipv4 || true)"
fi
BACKEND_URL="http://${HOST_IP:-localhost}:3001"
FRONTEND_URL_VAL="http://${HOST_IP:-localhost}:3000"
echo "Using host: ${HOST_IP:-localhost}"

# Also fetch supporting values for reference / migrate script
DB_ENDPOINT="$(fetch "/${SSM_ENV}/${SSM_APP}/db/endpoint" 2>/dev/null || true)"
DB_NAME="$(fetch "/${SSM_ENV}/${SSM_APP}/db/name" 2>/dev/null || true)"

cat > "$ROOT/scripts/.env" <<'ENVEOF'
# Generated by scripts/fetch-ssm-env.sh — do not edit manually.
# Re-run fetch-ssm-env.sh to refresh.
ENVEOF

# Append values with single-quotes to prevent Docker Compose variable interpolation
{
  echo "# RDS credentials (from SSM /${SSM_ENV}/${SSM_APP}/)"
  printf "DATABASE_URI='%s'\n" "$DATABASE_URI"
  printf "PAYLOAD_SECRET='%s'\n" "$PAYLOAD_SECRET"
  echo ""
  echo "# Informational (not used by compose directly)"
  printf "DB_ENDPOINT='%s'\n" "$DB_ENDPOINT"
  printf "DB_NAME='%s'\n" "$DB_NAME"
  echo ""
  echo "# Backend runtime"
  printf "PAYLOAD_URL='%s'\n" "$BACKEND_URL"
  printf "FRONTEND_URL='%s'\n" "$FRONTEND_URL_VAL"
  echo ""
  echo "# Frontend (build-time baked by frontend.Dockerfile)"
  printf "NEXT_PUBLIC_PAYLOAD_URL='%s'\n" "$BACKEND_URL"
  echo "# Server-side API URL (container -> backend hostname in Docker network)"
  echo "PAYLOAD_API_URL=http://backend:3001"
} >> "$ROOT/scripts/.env"

echo "scripts/.env written."
